### ISSUE TITLE
Java source/target of the project is at ancient level 1.6

### ISSUE THREAD

**Issue by pzygielo** [eclipse-ee4j/glassfish-copyright-plugin#14]
I think it could be set to at least 1.7 (which Maven is committed to support still).

AFAIK most of ee4j projects are at 1.8+ (e.g. mail has profile for 1.7, but I'm not sure if it is being used for the release).
Perhaps even 1.8 could be considered then?

Not sure if such (breaking) change should be followed by major version update as well.

**Comment by arjantijms** [comment]
I agree, 1.8 should be the absolutely minimum these days. I don't have a strong feeling about a major version update, but if you decide to do it, I'm okay with it.
